repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
        files: src
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        additional_dependencies: [pep8-naming>=0.11.1]
-   repo: local
    hooks:
    -   id: tests
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [push]
